### ISSUE TITLE
utf-8 support for translation

### ISSUE THREAD

**Issue by Behoston** [jacobmarshall/meloooncensor#29]
Translations does not support UTF-8
![zrzut ekranu z 2017-02-24 00-10-49](https://cloud.githubusercontent.com/assets/7823689/23283373/cd5687b0-fa25-11e6-84a2-8fcefd9a54cc.png)

**Comment by jmshal** [comment]
Thanks, I will make sure to fix this when I test the other changes you have made.

**Comment by Behoston** [comment]
Closed by:
https://github.com/jmshal/meloooncensor/commit/ff1c18b1128f1f8a9d99a4ecb8d7cbb0e2d68edc
